services:
  bot:
    # github registry
    # image: ghcr.io/gasoid/merge-bot:latest
    # dockerhub registry
    image: gasoid/merge-bot:latest
    restart: always
    volumes:
      - tls-cache:/tmp/tls/.cache
    ports:
      - "443:443"
      - "8080:8080"
    env_file:
      - bot.env
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1s

volumes:
  tls-cache:
