services:
  redis:
    image: redis:8.8
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 1s
  bot:
    # github registry
    # image: ghcr.io/gasoid/merge-bot:latest
    # dockerhub registry
    depends_on:
      - redis
    image: gasoid/merge-bot:3.10.2
    restart: always
    volumes:
      - tls-cache:/tmp/tls/.cache
    ports:
      - "443:443"
      - "8080:8080"
    env_file:
      - bot.env
    environment:
      REDIS_URL: "redis://redis:6379/0"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1s

volumes:
  tls-cache:
